CREATE OR REPLACE FUNCTION dropIfExists() RETURNS INTEGER AS '
BEGIN RETURN 1; END;' LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION dropIfExists(INTEGER) RETURNS INTEGER AS '
BEGIN RETURN $1; END;' LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION dropIfExists(TEXT, TEXT) RETURNS INTEGER AS '
BEGIN RETURN 1; END;' LANGUAGE 'plpgsql';
